### PR TITLE
Improve compile-times, remove warnings, & add some tests

### PR DESCRIPTION
**Pull request by qtdyn**

### CODE REVIEW

**Comment by Myresa** [comment]
Hello !

The new test #14 for ft_write() is broken on Lyon's campus and appears to not be portable between Linux versions. (We're on 5.4.0)

Both `write(p[1], NULL, 1)` and `ft_write(p[1], NULL, 1)` set `errno` to `EFAULT` (14) instead of the expected `EINVAL` (22).

Tested with:
```C
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include "libasm.h"

int main()
{
    int p[2];
    ssize_t ret;

    //printf("err: %d %d %d\n", EINVAL, EBADF, EFAULT);
    pipe(p);

    /* write */
    errno = 0;
    ret = write(p[1], NULL, 1);
    printf("write   : %ld %d\n", ret, errno);

    /* ft_write */
    errno = 0;
    ret = ft_write(p[1], NULL, 1);
    printf("ft_write: %ld %d\n", ret, errno);

    close(p[0]);
    close(p[1]);

    return (0);
}
```

Output:
```
write   : -1 14
ft_write: -1 14
```

If you want me to move this to an issue let me know

**Comment by Tripouille** [comment]
Salut,

Pourrais-tu si possible faire une pull request avec un correctif, car je ne
maintiens plus ce tester :/

Merci par avance.

**Comment by qtdyn** [comment]
> Hello !
> 
> The new test #14 for ft_write() is broken on Lyon's campus and appears to not be portable between Linux versions. (We're on 5.4.0)
> 
> Both `write(p[1], NULL, 1)` and `ft_write(p[1], NULL, 1)` set `errno` to `EFAULT` (14) instead of the expected `EINVAL` (22).
> 
> Tested with:
> 
> ```c
> #include <unistd.h>
> #include <stdio.h>
> #include <errno.h>
> #include "libasm.h"
> 
> int main()
> {
>     int p[2];
>     ssize_t ret;
> 
>     //printf("err: %d %d %d\n", EINVAL, EBADF, EFAULT);
>     pipe(p);
> 
>     /* write */
>     errno = 0;
>     ret = write(p[1], NULL, 1);
>     printf("write   : %ld %d\n", ret, errno);
> 
>     /* ft_write */
>     errno = 0;
>     ret = ft_write(p[1], NULL, 1);
>     printf("ft_write: %ld %d\n", ret, errno);
> 
>     close(p[0]);
>     close(p[1]);
> 
>     return (0);
> }
> ```
> 
> Output:
> 
> ```
> write   : -1 14
> ft_write: -1 14
> ```
> 
> If you want me to move this to an issue let me know

Whoops, je refais ça dans la semaine :+1:

**Comment by qtdyn** [comment]
@ArchaDust Si tu as moyen, tu peux tester [cette branche](https://github.com/xtrm-en/libasmTester) voir si ça fix?

**Pull request merged**
